# Generated by Django 5.1.6 on 2026-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_tenant_recetamedica_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='medicamentos_frecuentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='medico_habitual',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
