# Generated by Django 5.1.6 on 2026-05-22 06:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_tenant_recetamedica_tenant_and_more'),
        ('inventarios', '0006_categoria_tenant_entradastock_tenant_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_publico', models.CharField(max_length=160)),
                ('dosis_cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('unidad_dosis', models.CharField(max_length=40)),
                ('frecuencia_horas', models.PositiveIntegerField()),
                ('duracion_dias', models.PositiveIntegerField()),
                ('instrucciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tratamiento_base', to='inventarios.producto')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tratamiento base',
                'verbose_name_plural': 'Tratamientos base',
                'ordering': ['nombre_publico'],
            },
        ),
        migrations.CreateModel(
            name='TratamientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin_esperada', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('abandonado', 'Abandonado'), ('pausado', 'Pausado')], default='activo', max_length=20)),
                ('recordatorios_activos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_activos', to='clientes.cliente')),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('tratamiento_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_cliente', to='tratamientos.tratamientobase')),
            ],
            options={
                'verbose_name': 'Tratamiento activo',
                'verbose_name_plural': 'Tratamientos activos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TomaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_programada', models.DateTimeField(db_index=True)),
                ('fecha_hora_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('tomada', 'Tomada'), ('omitida', 'Omitida'), ('pospuesta', 'Pospuesta')], default='pendiente', max_length=20)),
                ('dosis_tomada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('tratamiento_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas', to='tratamientos.tratamientoactivo')),
            ],
            options={
                'verbose_name': 'Toma de medicamento',
                'verbose_name_plural': 'Tomas de medicamento',
                'ordering': ['fecha_hora_programada'],
                'indexes': [models.Index(fields=['estado', 'fecha_hora_programada'], name='tratamiento_estado_394c7f_idx'), models.Index(fields=['tratamiento_activo', 'fecha_hora_programada'], name='tratamiento_tratami_8eb3ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'tratamiento_activo', 'fecha_hora_programada'), name='uq_toma_tenant_tratamiento_programada')],
            },
        ),
        migrations.AddConstraint(
            model_name='tratamientobase',
            constraint=models.CheckConstraint(condition=models.Q(('frecuencia_horas__gte', 1)), name='chk_trat_base_frecuencia_min_1'),
        ),
        migrations.AddConstraint(
            model_name='tratamientobase',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_dias__gte', 1)), name='chk_trat_base_duracion_min_1'),
        ),
        migrations.AddIndex(
            model_name='tratamientoactivo',
            index=models.Index(fields=['cliente', 'estado'], name='tratamiento_cliente_bc6540_idx'),
        ),
        migrations.AddIndex(
            model_name='tratamientoactivo',
            index=models.Index(fields=['fecha_fin_esperada', 'estado'], name='tratamiento_fecha_f_ceca5a_idx'),
        ),
    ]
