# Generated by Django 5.1.6 on 2026-05-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('tratamientos', '0007_dispositivonotificacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispositivonotificacion',
            new_name='tratamiento_cliente_6a4f3e_idx',
            old_name='tratamientoc_cliente_1e2d0f_idx',
        ),
        migrations.RenameIndex(
            model_name='dispositivonotificacion',
            new_name='tratamiento_platafo_57f13d_idx',
            old_name='tratamientoc_platafo_a95d58_idx',
        ),
        migrations.AlterField(
            model_name='dispositivonotificacion',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
