# Generated by Django 5.1.6 on 2026-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_categoria_tenant_entradastock_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradastock',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
