# Generated by Django 5.1.6 on 2026-05-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0007_entradastock_referencia"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteProducto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_lote", models.CharField(max_length=100)),
                ("fecha_fabricacion", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("cantidad_inicial", models.PositiveIntegerField(default=0)),
                ("cantidad_disponible", models.PositiveIntegerField(default=0)),
                ("precio_compra", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("proveedor", models.CharField(blank=True, max_length=200)),
                ("estado", models.CharField(choices=[("disponible", "Disponible"), ("agotado", "Agotado"), ("vencido", "Vencido"), ("bloqueado", "Bloqueado"), ("danado", "Danado"), ("retirado", "Retirado")], default="disponible", max_length=20)),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("producto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lotes", to="inventarios.producto")),
                ("tenant", models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="tenants.tenant")),
            ],
            options={
                "verbose_name": "Lote de Producto",
                "verbose_name_plural": "Lotes de Producto",
                "ordering": ["producto", "fecha_vencimiento", "numero_lote"],
            },
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="stock_anterior",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="stock_posterior",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="lote",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movimientos", to="inventarios.loteproducto"),
        ),
        migrations.AddField(
            model_name="entradastock",
            name="estado",
            field=models.CharField(choices=[("pendiente", "Pendiente"), ("confirmada", "Confirmada"), ("anulada", "Anulada")], default="pendiente", max_length=20),
        ),
        migrations.AddField(
            model_name="entradastock",
            name="lote",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="entradas", to="inventarios.loteproducto"),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="producto",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimientos", to="inventarios.producto"),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="tipo_movimiento",
            field=models.CharField(choices=[("entrada", "Entrada"), ("salida", "Salida"), ("ajuste", "Ajuste")], max_length=20),
        ),
        migrations.AlterField(
            model_name="entradastock",
            name="producto",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entradas", to="inventarios.producto"),
        ),
        migrations.AlterField(
            model_name="entradastock",
            name="cantidad",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="entradastock",
            name="referencia",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="entradastock",
            name="lote",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entradas", to="inventarios.loteproducto"),
        ),
        migrations.AddConstraint(
            model_name="loteproducto",
            constraint=models.UniqueConstraint(fields=("tenant", "producto", "numero_lote"), name="uq_loteproducto_tenant_numero_lote"),
        ),
    ]

