# Generated by Django 5.1.6 on 2026-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_entradastock_compra_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproducto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('vencido', 'Vencido'), ('bloqueado', 'Bloqueado'), ('danado', 'Dañado'), ('retirado', 'Retirado')], default='disponible', max_length=20),
        ),
    ]
