# Generated by Django 5.1.6 on 2026-05-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_alter_loteproducto_estado'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE inventarios_entradastock DROP COLUMN IF EXISTS numero_lote;
                ALTER TABLE inventarios_entradastock DROP COLUMN IF EXISTS fecha_fabricacion;
                ALTER TABLE inventarios_entradastock DROP COLUMN IF EXISTS fecha_vencimiento;
                ALTER TABLE inventarios_entradastock DROP COLUMN IF EXISTS precio_compra;
                ALTER TABLE inventarios_entradastock DROP COLUMN IF EXISTS proveedor;
                ALTER TABLE inventarios_entradastock DROP COLUMN IF EXISTS compra_referencia;
            """,
            reverse_sql="""
                ALTER TABLE inventarios_entradastock ADD COLUMN IF NOT EXISTS numero_lote varchar(100) DEFAULT '';
                ALTER TABLE inventarios_entradastock ADD COLUMN IF NOT EXISTS fecha_fabricacion date NULL;
                ALTER TABLE inventarios_entradastock ADD COLUMN IF NOT EXISTS fecha_vencimiento date NULL;
                ALTER TABLE inventarios_entradastock ADD COLUMN IF NOT EXISTS precio_compra numeric(10,2) DEFAULT 0;
                ALTER TABLE inventarios_entradastock ADD COLUMN IF NOT EXISTS proveedor varchar(200) DEFAULT '';
                ALTER TABLE inventarios_entradastock ADD COLUMN IF NOT EXISTS compra_referencia varchar(100) DEFAULT '';
            """,
        ),
    ]
