# Generated by Django 5.1.6 on 2026-05-10 15:13

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
import tenants.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('limite_usuarios', models.PositiveIntegerField(default=3)),
                ('limite_productos', models.PositiveIntegerField(default=500)),
                ('limite_inventario_items', models.PositiveIntegerField(default=3000)),
                ('limite_almacenamiento_mb', models.PositiveIntegerField(default=512)),
                ('permite_reportes_ia', models.BooleanField(default=False)),
                ('permite_backups', models.BooleanField(default=False)),
                ('permite_predicciones', models.BooleanField(default=False)),
                ('stripe_price_id_mensual', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_price_id_anual', models.CharField(blank=True, default='', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_plan',
                'ordering': ['precio_mensual', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=160)),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('trial_start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_end_at', models.DateTimeField(default=tenants.models.default_trial_end_at)),
                ('paid_start_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], db_index=True, default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_tenant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('auto_renovar', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('trialing', 'Trial'), ('active', 'Activa'), ('past_due', 'Vencida'), ('canceled', 'Cancelada')], default='trialing', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='tenants.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_suscripcion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_domain',
            },
        ),
        migrations.CreateModel(
            name='TenantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('permisos', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_tenant_role',
                'ordering': ['nombre'],
                'unique_together': {('tenant', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('farmaceutico', 'Farmaceutico'), ('cajero', 'Cajero'), ('cliente', 'Cliente')], default='cliente', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants_tenant_user',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
