# Generated by Django 5.1.6 on 2026-05-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canjepuntos',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='catalogocanje',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='configuracionpuntos',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='cuentapuntos',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='transaccionpuntos',
            name='tenant',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
    ]
