# Generated by Django 5.1.6 on 2026-05-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_carritoitem_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cliente',
        ),
    ]
