# Generated by Django 5.1.6 on 2026-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0003_alter_campanapublicitaria_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanapublicitaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='campanas/'),
        ),
    ]
