# Generated by Django 5.1.6 on 2026-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automático')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('failed', 'Fallido')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('disabled', 'Desactivado'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='disabled', max_length=20)),
                ('time', models.TimeField(default='02:00')),
                ('active', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
