# Generated by Django 5.1.6 on 2026-05-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupSchedule',
        ),
        migrations.AlterModelOptions(
            name='backuplog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de Backup', 'verbose_name_plural': 'Registros de Backup'},
        ),
        migrations.AlterField(
            model_name='backuplog',
            name='backup_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automático')], default='manual', max_length=10),
        ),
    ]
