# Generated by Django 5.1.6 on 2026-05-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backuplog_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('hourly', 'Cada hora'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('custom', 'Expresión cron personalizada')], default='daily', max_length=20)),
                ('time_of_day', models.TimeField(blank=True, help_text='Hora del día (para diario/semanal/mensual). Formato HH:MM', null=True)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Día 0'), (1, 'Día 1'), (2, 'Día 2'), (3, 'Día 3'), (4, 'Día 4'), (5, 'Día 5'), (6, 'Día 6')], help_text='0=Domingo, 6=Sábado (para frecuencia semanal)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], help_text='Día del mes (para frecuencia mensual)', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text="Expresión cron (para frecuencia personalizada). Ej: '0 2 * * *'", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Programación de backup',
                'verbose_name_plural': 'Programaciones de backup',
            },
        ),
    ]
