// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNuwW4MHdEFS89bbi-MUCtUetVKrQ97k',
    appId: '1:814051808047:web:67850843fd994bac8d47da',
    messagingSenderId: '814051808047',
    projectId: 'farmacia-446f5',
    authDomain: 'farmacia-446f5.firebaseapp.com',
    storageBucket: 'farmacia-446f5.firebasestorage.app',
    measurementId: 'G-94ZCCKHPM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmjgabIJVu4gZGWcF8iyTG0dQj7f1PXYo',
    appId: '1:814051808047:android:e573fca891b3d0af8d47da',
    messagingSenderId: '814051808047',
    projectId: 'farmacia-446f5',
    storageBucket: 'farmacia-446f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkPyQvaOUP1bxXPHI-Y-KbUCSxVORmYUw',
    appId: '1:814051808047:ios:c103f76215ce9ab58d47da',
    messagingSenderId: '814051808047',
    projectId: 'farmacia-446f5',
    storageBucket: 'farmacia-446f5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkPyQvaOUP1bxXPHI-Y-KbUCSxVORmYUw',
    appId: '1:814051808047:ios:c103f76215ce9ab58d47da',
    messagingSenderId: '814051808047',
    projectId: 'farmacia-446f5',
    storageBucket: 'farmacia-446f5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnNuwW4MHdEFS89bbi-MUCtUetVKrQ97k',
    appId: '1:814051808047:web:3c5998a22b5450918d47da',
    messagingSenderId: '814051808047',
    projectId: 'farmacia-446f5',
    authDomain: 'farmacia-446f5.firebaseapp.com',
    storageBucket: 'farmacia-446f5.firebasestorage.app',
    measurementId: 'G-ERCDVNYBSE',
  );
}
